#!/bin/bash
#  _  _ _|  _   _
# (_ | (_| |_) (_|
#          |    
# top.md is what appears above the blog index and bottom.md below the index.
# it needs a style.css file in the root directory of the website

command -v pandoc >/dev/null 2>&1 || { echo >&2 "Pandoc not installed. Aborting."; exit 1; }

head=top.md
end=bottom.md
pandoc='pandoc --quiet -s --title=crdpa --highlight-style breezedark -c'
css='/styles.css'

if [ -f blog.md ]; then
    rm blog.md
    printf -- "# Blog\n" > blog.md
else
    printf -- "# Blog\n" > blog.md
fi

if [ -f tmp.md ]; then
    rm tmp.md
    touch tmp.md
else
    touch tmp.md
fi

# function that creates an index of posts
blog () {
        if [ -f "$f2" ] && [ ! -f "${f2::-3}.html" ]; then
            $pandoc "$css" -o "${f2::-3}.html" "$f2"
        fi
        l1=$(echo "${f2::-3}" | sed 's:.*/::')
        printf -- "- %s/[%s](%s)\n" "$y" "$l1" "${f2::-3}.html" >> tmp.md
}

# loop through all the markdown files writing the index
for f1 in "blog/"*; do
    y="${f1: -4}"
    for f2 in "blog/$y/"*.md; do
        blog
    done
done

# turn the index upside down
tac tmp.md >> blog.md
rm tmp.md

if [ -f "$head" ]; then
    {
        cat "$head"
    	echo ""
    	cat blog.md
    } > index.md
else
    cat blog.md > index.md
fi

if [ -f "$end" ]; then
    {
        echo ""
    	cat "$end"
    } >> index.md
fi

$pandoc styles.css -o index.html index.md

echo "Done..."
              
